version: '3'

services:
  postgres:
    image: postgres:alpine
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 12
        POSTGRES_DB: aftas
    ports:
        - "5432:5432"

  spring-app:
    build:
      context: ./backend aplication/aftas
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/aftas?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12

  spring-app-angular:
    build:
      context: ./front end application/aftas
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - spring-app
