# Server Configuration

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Aftas?createDatabaseIfNotExist=true
    username: postgres
    password: 12
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
